### ISSUE TITLE
always use remote docs when replicating integrated data

### ISSUE THREAD

**Issue by jjal** [fielded/angular-nav-data#43]
When integrated data is updated out of sequence (e.g. by an import) remotely local replication will frequently choose the local doc, as the imported doc will have a lower rev owing to its being created from scratch. 

This leads to changes by etl (e.g. importing missed levels) being ignored by local databases.

- [ ] replication of integrated data should always accept remote changes regardless of difference in revision number

**Comment by jjal** [comment]
Is this useful? http://stackoverflow.com/questions/18434686/how-to-resolve-conflicts-with-continuous-replication

- if always deleting the local doc for which there is a conflict, replication will continue by writing the remote doc right?

**Comment by patriciagarcia** [comment]
Afaik deleting the doc locally will only create a new revision and that revision will most probably become the winning revision again and the doc will stay deleted. If we would be able to purge the local doc from the db, then the doc will have to be replicated again with the copy from the database, but that is not possible yet in PouchDB (it would also be inefficient because it requires syncing the remote copy twice).

The way to handle conflicts is to delete what we consider to be the losing revision, i.e. the local revision in this case. Explanation here, see [Eventual conflicts section](https://pouchdb.com/guides/conflicts.html).

A createAt/updateAt property will make this straightforward and since we need to recreate the integrated-data database anyway, it won't make too much difference.

Actually even if we recreate the remote database and the remote revs are reset to rev `1-x`, the local docs will still contain several revs, which makes the database bigger and slower. I am having a look at using auto compaction to prevent this.

**Comment by freefony** [comment]
Issues
 - CouchDB replication algorithm does not guarantee that update weekly levels are written to localDBs.  

Aim
 - ALWAYS update local `weekly stock` levels with remote `weekly stock levels`  values irrespective of versions
  

- [ ]  For docs with no `updatedAt` property,  delete losing revisions. (`db.remove`)
- [ ] For docs with `updatedAt` property, reduce conflicting docs to one array, sort by `updatedAt` and pick the most recent as winner.

Test
  - On `integrated-data` DB, edit and save docs with properties `type:  product && updatedAt: 'xxx'`  on CouchDB(Remote). Also edit and save docs with properties `type: 'location' && updatedAt: 'xxx'` with the documents on the remoteDB having a lower `_rev` level. 
 - Open the `Nav-integrated-state-dashboard` with for replication to complete. 
    Expected Outcomes 
    - If the fix is NOT applied, localDB revisions will win for having newer versions. 
   - If the fix is applied, The doc should have values of the revision with the most recent `updatedAt` and no revisions conflicting with the current `_rev`.

**Comment by patriciagarcia** [comment]
Thanks Femi! Just adding a bit more detail here:

Since we're going to add an `updatedAt` property to all docs, the most likely case is that one of the rev has an `updateAt` property and the other hasn't. The one with the `updatedAt` property should be chosen as the winning one.
>  For docs with no updatedAt property, delete losing revisions. (db.remove)

**Comment by jjal** [comment]
Hey Femi good start, needs more specificity: 
- please change the test to use a  remote doc with a lower rev, meaning that it will always lose unless the fix is put in place. Otherwise your test could sometimes pass without the problem being fixed
- can you also specify the null case (prior to fix, what would you expect to happen - remote doc that is more recent, but with a lower rev, will not be replicated locally)
- please specify the database and doc type so that it targets the reported problem and module - locations, integrated-data
- how would you commit the doc?
- how would you sync both DBs?

Please write that out in the test first
